
# - name: checkout repo
#         uses: actions/checkout@v3

name: 1-My First Workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      ## steps
    
      - name: Welcome message
        run: echo "My first Github Actions Job"
      - name: List files
        run: ls
      - name: Read file
        run: cat README.md