name: 2-Generate ascii cowsay
on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

        
      - name: List Repo Files
        run: ls -ltra

      - name: Executing Shell Script
        run: |                         # | for MultiLine commands
            chmod +x script.sh
            ./script.sh