name: 3-Run Multiple Jobs
on:
  #  push:
   workflow_dispatch:


  
jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      # - name: Upload Dragon file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dragon-txt-file
      #     path: dragon.txt

  test_job_2:
    
    runs-on: ubuntu-latest
    needs: [build_job_1]
    steps:
      # - name: Download Dragon File
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: dragon-txt-file
      #     path: ./artifact
    
    ##Find the file
      - name: Test File Exists
        run: grep -i "dragon" ./artifact/dragon.txt

  deploy_job_3:
    runs-on: ubuntu-latest
    needs: [build_job_1,test_job_2]
    steps:
      # - name: Download Dragon File
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: dragon-txt-file
      #     path: ./artifact

    ##Read the file
      - name: Read File
        run: cat ./artifact/dragon.txt

      - name: Deploy
        run: echo "Deploying ......"
